- name: Ensure gradle-wrapper.properties is correct
        run: |
          mkdir -p gradle/wrapper
          if [ ! -f gradle/wrapper/gradle-wrapper.properties ]; then
            echo "gradle-wrapper.properties not found, creating..."
            cat <<EOF > gradle/wrapper/gradle-wrapper.properties
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https://services.gradle.org/distributions/gradle-8.14.3-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
EOF
          else
            echo "gradle-wrapper.properties exists, verifying..."
            grep -q "distributionUrl=" gradle/wrapper/gradle-wrapper.properties || echo "distributionUrl=https://services.gradle.org/distributions/gradle-8.14.3-bin.zip" >> gradle/wrapper/gradle-wrapper.properties
          fi
